server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/splitwise
    username: postgres
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_jMJ4AX76k
