import { Stack, StackProps, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { exportParam } from '../utils/parameter-utils';

interface SplitwiseAlbStackProps extends StackProps {
  appName: string;
  envName: string;
  vpc: ec2.Vpc;
  albSecurityGroup: ec2.SecurityGroup;
}

export class SplitwiseAlbStack extends Stack {
  public readonly targetGroup: elbv2.ApplicationTargetGroup;
  public readonly internalTokenSecretArn: string;

  constructor(scope: Construct, id: string, props: SplitwiseAlbStackProps) {
    super(scope, id, props);

    const { appName, envName, vpc, albSecurityGroup } = props;
    const domainName = 'splitwise-network';

    // =========================================================
    // Internal Token for API Gateway -> ALB Auth
    //
    // Automatically generated by Secrets Manager.
    // ALB uses this value in a listener rule condition.
    // API Gateway will retrieve it and inject it as a header.
    // =========================================================
    const internalTokenSecret = new secretsmanager.Secret(this, 'InternalTokenSecret', {
      secretName: `/${appName}/${envName}/splitwise/internal-token`,
      description: 'Secret token used to authenticate API Gateway to ALB',
      generateSecretString: {
        passwordLength: 32,
        excludePunctuation: true // Keep it alphanumeric for HTTP headers
      }
    });
    this.internalTokenSecretArn = internalTokenSecret.secretArn;

    // =========================================================
    // Target Group
    // =========================================================
    this.targetGroup = new elbv2.ApplicationTargetGroup(this, 'TargetGroup', {
      targetGroupName: `${appName}-${envName}-splitwise-tg`,
      vpc,
      targetType: elbv2.TargetType.IP,
      port: 8080,
      protocol: elbv2.ApplicationProtocol.HTTP,
      healthCheck: {
        path: '/health',
        protocol: elbv2.Protocol.HTTP,
        healthyHttpCodes: '200',
        interval: Duration.seconds(30),
        timeout: Duration.seconds(30),
        healthyThresholdCount: 2,
        unhealthyThresholdCount: 3
      },
      deregistrationDelay: Duration.seconds(10)
    });

    // =========================================================
    // Application Load Balancer
    // =========================================================
    const alb = new elbv2.ApplicationLoadBalancer(this, 'Alb', {
      loadBalancerName: `${appName}-${envName}-splitwise-alb`,
      vpc,
      internetFacing: true,
      securityGroup: albSecurityGroup,
      vpcSubnets: { subnetType: ec2.SubnetType.PUBLIC }
    });

    // =========================================================
    // ALB Listener + Secret Header Rule
    // =========================================================
    const listener = alb.addListener('HttpListener', {
      port: 80,
      protocol: elbv2.ApplicationProtocol.HTTP,
      defaultAction: elbv2.ListenerAction.fixedResponse(403, {
        contentType: 'application/json',
        messageBody: '{"error":"Forbidden"}'
      })
    });

    listener.addAction('SecretHeaderRule', {
      priority: 1,
      conditions: [
        // Automatically injects the CloudFormation dynamic reference to the secret.
        elbv2.ListenerCondition.httpHeader('X-Internal-Token', [internalTokenSecret.secretValue.unsafeUnwrap()])
      ],
      action: elbv2.ListenerAction.forward([this.targetGroup])
    });

    exportParam(this, appName, envName, domainName, 'alb-dns-name', alb.loadBalancerDnsName);
    exportParam(this, appName, envName, domainName, 'target-group-arn', this.targetGroup.targetGroupArn);
    exportParam(this, appName, envName, domainName, 'internal-token-secret-arn', internalTokenSecret.secretArn);
  }
}
